### ISSUE TITLE
Crashing when autosizing a huge amount of textareas.

### ISSUE THREAD

**Issue by bierik** [janjarfalk/jquery-elastic#27]
In my case I want to autosize about ```200``` textareas. The loading time takes a long time and the browser crashes when starting to type. This plugin's performace is better and works for me: http://www.jacklmoore.com/autosize/
Probably you could check his implementation.

**Comment by janjarfalk** [comment]
Being able to handle 200 textareas at once has not been a goal for Elastic. I think you should stick with autosize if that works better for you.
